pankod/superplate

- src/saofile.ts
> Handle prompt.js

- src/Helper/plugin/index.ts
> Handle confirm prompt type

- package.json
- template/_package.json
- template/next.config.js
pushlarken `<%_` gibi syntaxlara kızdığı için no-verify dedim (bu bir itiraftır :( )
> Compose less plugin 

- documentation/docs/tailwind.md
> add postcss config to tailwind docs

- documentation/docs/testing/jest.md
> add example test jest

- documentation/sidebars.js
> match order with prompts

- documentation/docusaurus.config.js
- documentation/src/pages/index.js
> Fixed Landing issues

- package-lock.json
- template/_package.json
> upgrade nextjs version

- template/_package.json
> update next.js and react

- package.json
- src/Helper/binary/index.spec.ts
- src/Helper/binary/index.ts
- src/Helper/index.ts
- src/saofile.ts
Only ask for package manager if `yarn` is installed, otherwise skip.
> Check if `yarn` installed before asking

- documentation/docs/nextjs/ci/azure-pipelines.md
pankod/superplate-core-plugins#202
> AzurePipelines docs for pankod/superplate-core-plugins#202

- @types/sao.d.ts
- README.MD
- documentation/docs/development/references.md
- jest.config.ts
- package-lock.json
- package.json
- src/Helper/binary/index.ts
- src/Helper/git/index.spec.ts
- src/Helper/git/index.ts
- src/Helper/index.ts
- src/Helper/lucky/index.ts
- src/Helper/preset/index.ts
- src/Helper/source/index.ts
- src/cli.ts
- src/saofile.ts
`--branch, -b`: specify a branch in the source (needs to be git ofc)
`--preset, -o`: select a preset to auto fill the questions, those need to be defined in the `source > prompt.js > presets`
`--lucky, -l`: (Easter egg) if you are feeling lucky, this option will randomly select some choices for you.
> feat: `--branch` `--preset` and `--lucky` options

- package-lock.json
- package.json
- src/Helper/download/index.ts
- src/Helper/index.ts
- src/Helper/source/index.ts
- src/cli.ts
Added zip support
`npx superplate-cli -d zip` or `npx superplate-cli --download zip`
> feat: add zip support

- documentation/src/pages/index.js
Change `usefull` (obsolete) to `useful` (correct term).
> fix: fix grammar error

- @types/sao.d.ts
- package-lock.json
- package.json
- src/Helper/prettier/index.ts
- src/api.ts
- src/cli.ts
- src/saofile.ts
- Added apiMode to SAO Config for skipping certain steps on api mode.
- Added api.ts to use with API
- Updated SAOFile
> Add api mode

- .github/reviewer-lottery.yml
- package-lock.json
- package.json
- src/api.ts
- src/saofile.ts
- Added "main" field to package.json to use it as a library.
- Fixed wrong parameter being passed to SAO class.
- Destructure answers into presetAnswers
> Fix: Api Mode

- .prettierrc
- package-lock.json
- package.json
- src/Helper/prettier/index.ts
Clears unused imports for prettier.
> feat: organize-imports plugin for prettier

- src/saofile.ts
Added missing deletions from PR #333
> fix: remove non plugins

- package-lock.json
- package.json
- src/saofile.ts
Wrapped segment track call with `try...catch` block to avoid showing error on user side.
> fix: error handling on telemetry call

- @types/sao.d.ts
- package-lock.json
- package.json
- src/api.ts
- src/cli.ts
- src/saofile.ts
Added `INITIAL_COMMIT_MESSAGE` env for the CLI and `commitMessage` property for the API mode to customize the initial commit message.
> feat: ability to change commit message

- package-lock.json
- package.json
- src/saofile.ts
Wrap project creation request with try/catch.
Also refactored variables names.
> fix: project creation

- package-lock.json
- package.json
- src/saofile.ts
> fix: telemetry URL

- package.json
- src/Helper/tips/index.ts
> chore: update post install message

- package-lock.json
- package.json
- src/saofile.ts
when used with apiMode, process was hanging because we were asking email prompt.
> fix: skip email prompt for `apiMode`

- .gitignore
- package-lock.json
- package.json
- src/saofile.ts
- tsconfig.json
Added the following fields to project POST request body:
- Source
- Answers
> feat: update project creation payload
